#based off of default.sdf location
#(lat, lon, cls_id)
locations:
  - [47.397971057728974, 8.546163739800146, 0]
  - [47.397981057728974, 8.546173739800146, 1]
  - [47.397991057728974, 8.546183739800146, 2]
  - [47.397981057728974, 8.546173739800146, 3]
  - [47.397971057728974, 8.546163739800146, 4]
