points:
  - [38.3876112, -76.4190542, 0]
  - [38.3876112, -76.4190542, 1]
  - [38.3876112, -76.4190542, 2]
  - [38.3876112, -76.4190542, 3]
  - [38.3876112, -76.4190542, 4]
  - [38.3876112, -76.4190542, 5]
